# .gitlab-ci.yml
stages:
 - build
 - deploy
variables:
 DOCKER_HOST: tcp://docker:2375/  # Specify Docker host address
build_image:
 stage: build
 image: docker:latest
 services:
   - docker:dind
 script:
   - docker build -t my-python-web-app .
deploy_container:
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - docker run -d -p 5000:5000 --name my-app-container my-python-web-app